id: PC766D4CC
initial_creation_type: ocr
source_metadata:
  volumes:
    a50d99b13d474ff9985752332471d6a4:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: ཆོས་རྗེས་སུ་དྲན་པའི་འགྲེལ་པ།
      total_pages: 1498
      volume_number: 65
